# Generated by Django 2.2.7 on 2019-11-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20191111_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='counrty',
            new_name='country',
        ),
    ]
