# Generated by Django 2.2.7 on 2019-11-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20191112_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='rooms_photos'),
        ),
    ]
